<!-- Rejoindre l'équipe -->
<h2 class="h_rejoindre_equipe">Rejoindre l'équipe</h2>
<p>L'équipe est prête à accueillir quiconque souhaite apporter sa contribution. Voici les différentes manières d'intégrer l'équipe :</p>
<ul>
	<li>Développeur : développer des fonctionnalités et corriger des erreurs</li>
	<li>Testeur : effectuer une batterie de tests des nouvelles fonctionnalités</li>
	<li>Rédacteur : rédiger de la documentation à destination des utilisateurs</li>
	<li>Accompagnateur : aider les utilisateurs dans leur utilisation de l'application</li>
</ul> 
<p>Pour rejoindre l'équipe, <a href="<?php echo Request::buildURL(null,'index','contact'); ?>">contactez-nous</a> en précisant vos motivations pour le(s) rôle(s) que vous désirez remplir.</p>

<!-- Signaler des erreurs -->
<h2 class="h_signaler_erreurs">Signaler des erreurs</h2>
<p class="p_construct">En construction...</p>

<!-- Proposer des améliorations -->
<h2 class="h_proposer_ameliorations">Proposer des améliorations</h2>
<p class="p_construct">En construction...</p>

<!-- Promouvoir le projet -->
<h2 class="h_promouvoir_projet">Promouvoir le projet</h2>
<p class="p_construct">En construction...</p>

<!-- Effectuer un don -->
<h2 class="h_effectuer_don">Effectuer un don</h2>
<p class="p_construct">En construction...</p>