<!DOCTYPE html>
<html>
	<head>
		<!-- Titre -->
		<title>ContestOrg - Le logiciel pour organiser tous vos tournois</title>
		
		<!-- Favicon -->
		<link rel="shortcut icon" type="image/x-icon" href="<?php echo Request::getBase(); ?>media/farm/32x32/sport.png" />
		
		<!-- Librairies CSS -->
		<link rel="stylesheet" type="text/css" href="<?php echo Request::getBase(); ?>css/main.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo Request::getBase(); ?>css/titles.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo Request::getBase(); ?>css/messages.css" />
		
		<!-- Librairies JS -->
		<script type="text/javascript" src="<?php echo Request::getBase(); ?>js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo Request::getBase(); ?>js/jquery.fancybox/jquery.fancybox-1.3.4.pack.js"></script>
		<script type="text/javascript" src="<?php echo Request::getBase(); ?>js/jquery.fancybox/jquery.easing-1.4.pack.js"></script>
		<script type="text/javascript" src="<?php echo Request::getBase(); ?>js/jquery.fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
		<link rel="stylesheet" href="<?php echo Request::getBase(); ?>js/jquery.fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
		
		<!-- Quand le DOM de la page est prêt -->
		<script type="text/javascript">
			$(document).ready(function() {
				// Images fancybox
				$('a.fancybox').fancybox({
					transitionIn:'elastic',
					transitionOut:'elastic',
					titlePosition:'over'
				});

				// Présentation youtube
				$('#youtube').fancybox({
					transitionIn:'elastic',
					transitionOut:'elastic',
					type:'swf',
					'swf':{'wmode':'transparent','allowfullscreen':'true'},
					titleShow:false,
					width:640,
					height:390
				});
			});
		</script>
		
		<!-- Balises meta -->
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8;" />
		<meta http-equiv="Content-Language" content="fr" />
		<meta http-equiv="Description" content="ContestOrg est un logiciel d’organisation de tournois : football, judo, rugby… En quelques clics, créez les participants, générez les séries de matchs et renseignez les résultats." />
		<meta http-equiv="Keywords" content="logiciel software concours tournois organisation organiser équipes joueurs participants matchs phases qualificatives éliminatoires finales sportif exportation diffusion publication FTP HTTP PDF site web mise mettre en ligne résultats football rugby judo pétanque belote" />
		<meta http-equiv="Subject" content="Logiciel d'organisation de tournois" />
		
		<!--  Code analytics -->
		<script type="text/javascript">
		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-9937933-7']);
		  _gaq.push(['_trackPageview']);
		
		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		</script>
	</head>
	<body>
		<!-- Page -->
		<div id="page">
			<!-- Entete -->
			<div id="header">
				<div id="title" onclick="window.location='<?php echo Request::getBase(); ?>';" title="Se rendre sur la page d'accueil">
					<h1>ContestOrg</h1>
				</div>
				<div id="subtitle">
					<p>Le logiciel pour organiser tous vos tournois</p>
				</div>
			</div>
			
			<!-- Menu -->
			<div id="menu">
				<ul>
					<li><a class="button" href="<?php echo Request::buildURL(null,'actualites','index'); ?>" title="Afficher les actualités">Actualités</a></li>
					<li><a class="button" href="<?php echo Request::buildURL(null,'documentation','index'); ?>" title="Consulter la documentation">Documentation</a></li>
					<li><a class="button" href="<?php echo Request::buildURL(null,'telecharger','index'); ?>" title="Accéder à la page de téléchargement">Télécharger</a></li>
					<li><a class="button" href="<?php echo Request::buildURL(null,'forum','index'); ?>" title="Accéder au forum">Forum</a></li>
					<li><a class="button" href="<?php echo Request::buildURL(null,'contribuer','index'); ?>" title="Contribuer au projet">Contribuer</a></li>
				</ul>
			</div>
			
			<!-- Contenu de la page -->
			<div id="content">
				<?php echo $this->content; ?>
			</div>
			
			<!-- Pied de page -->
			<div id="footer">
				<p>
					<a href="<?php echo Request::buildURL(null,'index','connexion'); ?>" title="Se connecter à son compte">Se connecter</a>
					-
					<a href="<?php echo Request::buildURL(null,'index','contact'); ?>" title="Se rendre sur le formulaire de contact">Contact</a>
					-
					<a href="<?php echo Request::buildURL(null,'index','credits'); ?>" title="Consulter les crédits">Crédits</a>
				</p>
			</div>
		</div>
	</body>
</html> 