<h2 class="title t_contact">Contact</h2>
<?php 

// Vérifier si le formulaire n'a pas été envoyé 
if(empty($this->success)) {
	// Vérifier si erreur
	if(isset($this->success)) {
		echo '<p class="message m_error">Erreur lors de l\'envoie du message</p>';
	}
	
	// Largeurs des champs 
	$this->form->nom->addAttributes('style="width:400px;"');
	$this->form->email->addAttributes('style="width:400px;"');
	$this->form->sujet->addAttributes('style="width:400px;"');
	$this->form->message->addAttributes('style="width:400px;"');
	
	// Afficher le formulaire
	echo $this->form;
} else {
	// Message de réussite
	echo '<p class="message m_success">Votre message a bien été envoyé</p>';
}

?>
<p class="comment">Vous pouvez contacter l'équipe en envoyant un email directement à <a href="mailto:<?php echo $this->email; ?>"><?php echo $this->email; ?></a>.</p>