<h2 class="h_credits">Crédits</h2>
<p>ContestOrg n'existerait pas sans de généreux développeurs ayant contribuer au développement de librairies dont voici la liste :</p>
<ul>
	<li><a href="http://www.jgraph.com/">jGraph</a> : Réalisation de graphes,	BSD</li>
	<li><a href="http://www.jdom.org/">jDom</a> : Manipulation du DOM XML, ~Apache License</li>
	<li><a href="http://www.junit.org/">jUnit</a> : Réalisation de tests unitaires, Common Public License 1.0</li>
	<li><a href="http://xmlgraphics.apache.org/fop/">FOP</a> : Processeur FOP, Apache License</li>
	<li><a href="http://hc.apache.org/">HttpComponents</a> : Création d'un serveur et de requêtes HTTP, Apache License</li>
	<li><a href="http://commons.apache.org/net/">Commons Net</a> : Etablissement de requêtes FTP..., Apache License</li>
	<li><a href="http://logging.apache.org/log4j/">Log4J</a> : Persistance de traces d'éxecution, Apache License</li>
	<li><a href="http://saxon.sourceforge.net/">Saxon</a> : Processeur XSLT autonome, Mozilla Public License 1.0</li>
</ul>

<p>N'oublions la liste des outils utilisés tout le long du développement de ContestOrg :</p>
<ul>
	<li><a href="http://www.eclipse.org/">Eclipse</a> : Environnement de développement intégré</li>
	<li><a href="http://code.google.com/">Google Code</a> : Plateforme de développement collaboratif</li>
	<li><a href="http://www.topcased.org/">TopCased</a> : Outil de modélisation basé sur Eclipse</li>
	<li><a href="http://www.docbook.org/">DocBook</a> : Langage à destination de documentation technique</li>
	<li><a href="http://www.xmlmind.com/xmleditor/">XMLMind</a> : Editeur XML prenant en charge la DTD DocBook</li>
	<li><a href="http://launch4j.sourceforge.net/">Launch4j</a> : Encapsuleur EXE pour JAR à destination de Windows</li>
	<li><a href="http://pencil.evolus.vn/">Pencil</a> : Logiciel de maquettes d'interfaces graphiques</li>
	<li><a href="http://inkscape.org/">Inkscape</a> : Editeur de graphismes vectoriels</li>
	<li><a href="http://optipng.sourceforge.net/">OptiPNG</a> : Optimiseur pour images PNG</li>
	<li><a href="http://pngnq.sourceforge.net/">Pngnq</a> : Optimiseur pour images PNG</li>
</ul>

<p>Pour finir, citons le pack d'icônes utilisé dans l'application et sur le site web :</p>
<ul>
	<li><a href="http://www.fatcow.com/">Farm</a> : Creative Commons Attribution 3.0</li>
</ul>