<h2 class="title t_documentation">Documentation</h2>

<p>Séléctionnez le format de documentation parmis la liste ci-dessous :</p>

<ul class="buttons">
	<li><a href="<?php echo Request::getBase(); ?>data/documentation/documentation.pdf" class="button">Documentation PDF</a></li>
	<li><a href="<?php echo Request::getBase(); ?>data/documentation/documentation.html" class="button">Documentation HTML</a></li>
	<li><a href="<?php echo Request::getBase(); ?>data/documentation/documentation.chm" class="button">Documentation CHM</a></li>
	<li><a href="<?php echo Request::getBase(); ?>data/documentation/documentation.xml" class="button">Documentation XML</a></li>
</ul>

<p><i>La documentation XML est réalisée à partir de la DTD <a href="http://www.docbook.org/">DocBook</a></i></p>