<h2 class="title t_telecharger">Télécharger</h2>

<p>Séléctionnez le fichier à télécharger selon votre plateforme :</p>

<ul class="buttons">
	<li><a href="http://contestorg.googlecode.com/files/ContestOrg-2.3.0-exe.zip" class="button">ContestOrg 2.3.0 (Windows)</a></li>
	<li><a href="http://contestorg.googlecode.com/files/ContestOrg-2.3.0-jar.zip" class="button">ContestOrg 2.3.0 (Linux)</a></li>
	<li><a href="http://contestorg.googlecode.com/files/ContestOrg-2.3.0-jar.zip" class="button">ContestOrg 2.3.0 (Mac)</a></li>
</ul>

<h2 class="title t_livre_or" id="livredor">Livre d'or</h2>
<?php

// Vérifier si le formulaire n'a pas été envoyé 
if(!$this->form->isValid()) {
	// Encourager l'ajout de message
	echo '<p>N\'hésitez pas à laisser un message sur le livre d\'or :</p>';
	
	// Vérifier si erreur
	if(isset($this->success)) {
		echo '<p class="message m_error">Erreur lors de l\'ajout du message</p>';
	}
	
	// Action
	$this->form->setAction('#livredor');
	
	// Largeurs des champs 
	$this->form->prenom->addExtra('style="width:400px;"');
	$this->form->email->addExtra('style="width:400px;"');
	$this->form->message->addExtra('style="width:400px;"');
	
	// Afficher le formulaire
	echo $this->form;
} else {
	// Message de réussite
	echo '<p class="message m_success">Merci d\'avoir signé notre livre d\'or</p>';
}

// Liste des signatures
echo '<h3 id="messages">Messages</h3>';
if($this->paginator->getCount() != 0) {
	foreach($this->paginator as $signature) {
		echo '<b>',date('d/m/Y',$signature->getDate()),' : ',$signature->getPrenom(),'</b><p>',$signature->getMessage(),'</p>';
	}
	$this->partial('pagination',array('paginator' => $this->paginator,'anchor' => 'messages'));
} else {
	echo 'Pas de messages';
}

?>