<h2 class="title t_actualites">Actualités</h2>
<h3>26/03/2012 - Lancement de ContestOrg 2.0.0 en version finale !</h3>
<p>
	Après de longs mois d'effort, une version alpha et une version beta, ContestOrg 2.0.0 voit
	enfin le jour en version finale. Ce fut l'occasion de prendre en compte de nombreux retours
	d'utilisateurs. Il s'agit principalement de corrections d'anomalies et d'ajouts de fonctionnalités
	parmis lesquelles nous retrouvons notamment : module d'inscription des équipes, tirage des poules
	par "chapeaux", vérification automatique d'une mise à jour, ... Nous espérons que cette version
	conviendra à vos besoin ! ;)
</p>