<h2 class="title t_actualites">Actualités</h2>
<h3>12/06/2012 - Correctif avec ContestOrg 2.3.1</h3>
<p>
	Suite à la mise à jour sortie hier, une anomalie s'est glissée au niveau de la saisie des résultats
	d'un match. C'est désormais corrigé avec la version 2.3.1.
</p>
<h3>11/06/2012 - Sortie de ContestOrg 2.3.0</h3>
<p>
	Il y a trois mois sortait la version finale de ContestOrg 2.0.0. Depuis, de nombreux utilisateurs
	ont proposé des améliorations et signalé des anomalies. Un grand merci à eux car cela contribue
	grandement à l'amélioration de l'application. Ainsi la nouvelle version 2.3.0 de ContestOrg sort
	aujourd'hui ! Parmi les évolutions, nous retrouvons de nouvelles exportations, une nouvelle diffusion,
	la possibilité de spécifier la date et le lieu d'un match. Des anomalies ont également été corrigées
	au nombre de quatre. N'hésitez pas à lire le fichier "lisez-moi.html" présent dans le répertoire de
	ContestOrg 2.3.0 pour plus d'informations. Bon tournoi !
</p>
<h3>26/03/2012 - Lancement de ContestOrg 2.0.0 en version finale !</h3>
<p>
	Après de longs mois d'effort, une version alpha et une version beta, ContestOrg 2.0.0 voit
	enfin le jour en version finale. Ce fut l'occasion de prendre en compte de nombreux retours
	d'utilisateurs. Il s'agit principalement de corrections d'anomalies et d'ajouts de fonctionnalités
	parmis lesquelles nous retrouvons notamment : module d'inscription des équipes, tirage des poules
	par "chapeaux", vérification automatique d'une mise à jour, ... Nous espérons que cette version
	conviendra à vos besoin ! ;)
</p>